### Create a new user
POST http://localhost:3000/auth
content-type: application/json

{
  "email": "jeremybearemy@example.com",
  "password": "test123"
}

### Create a new user with invalid email
POST http://localhost:3000/auth
content-type: application/json

{
  "email": "jeremybearemy",
  "password": "test123"
}

### Create a new user with incomplete fields
POST http://localhost:3000/auth
content-type: application/json

{
  "email": "jeremybearemy@example.com"
}

### Create a new user with incomplete fields
POST http://localhost:3000/auth
content-type: application/json

{
  "password": "test123"
}

### Create a new user with extraneous properties
POST http://localhost:3000/auth
content-type: application/json

{
  "email": "jeremybearemy@example.com",
  "password": "test123",
  "additional": "1234"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find a user that does not exist
GET http://localhost:3000/auth/1000000

### Find user by email
GET http://localhost:3000/auth?email=jeremybearemy@example.com

### Find not existent users by email
GET http://localhost:3000/auth?email=doesnotexist@example.com

### Delete user
DELETE http://localhost:3000/auth/3

### Update user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "jeremybearemy2updated@example.com"
}

### Update user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "password": "test1234"
}
