### Create a new user
POST http://localhost:3000/auth/sign-up
content-type: application/json

{
  "email": "jeremybearemy@example.com",
  "password": "test123"
}

### Create a new user with invalid email
POST http://localhost:3000/auth/sign-up
content-type: application/json

{
  "email": "jeremybearemy",
  "password": "test123"
}

### Create a new user with incomplete fields
POST http://localhost:3000/auth/sign-up
content-type: application/json

{
  "email": "jeremybearemy@example.com"
}

### Create a new user with incomplete fields
POST http://localhost:3000/auth/sign-up
content-type: application/json

{
  "password": "test123"
}

### Create a new user with extraneous properties
POST http://localhost:3000/auth/sign-up
content-type: application/json

{
  "email": "jeremybearemy@example.com",
  "password": "test123",
  "additional": "1234"
}

### Sign in with correct credentials
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "jeremybearemy@example.com",
  "password": "test123"
}

### Sign in with incorrect password
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "jeremybearemy@example.com",
  "password": "invalidpassword"
}

### Sign in with incorrect email
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "nonexistent@example.com",
  "password": "test123"
}

### Who am I
GET http://localhost:3000/auth/whoami

### Sign Out
POST http://localhost:3000/auth/sign-out

### Find a particular user with a given ID
GET http://localhost:3000/auth/user/6

### Find a user that does not exist
GET http://localhost:3000/auth/user/1000000

### Find user by email
GET http://localhost:3000/auth/user?email=jeremybearemy@example.com

### Find not existent users by email
GET http://localhost:3000/auth/user?email=doesnotexist@example.com

### Delete user
DELETE http://localhost:3000/auth/user/1

### Update user
PATCH http://localhost:3000/auth/user/2
content-type: application/json

{
  "email": "jeremybearemy2updated@example.com"
}

### Update user
PATCH http://localhost:3000/auth/user/2
content-type: application/json

{
  "password": "test1234"
}

# ### Set a color property in session cookie
# GET http://localhost:3000/auth/colors/red

# ### Get color property from session cookie
# GET http://localhost:3000/auth/colors